### ISSUE TITLE
1.1.1 Release seems to require aws_token

### ISSUE THREAD

**Issue by drakemccabe** [agawronski/pandas_redshift#15]
### Expected Behaviour

Expected 'aws_session_token' parameter to be optional when connecting to S3.

### Actual Behaviour

While using aws_access_key_id and aws_secret_access_key to connect to S3 and write to Redshift, this error occurs:

```
  File "/usr/local/lib/python3.4/site-packages/pandas_redshift/core.py", line 111, in pandas_to_redshift
    if aws_token:
NameError: name 'aws_token' is not defined
```

**Comment by agawronski** [comment]
Taking a look now.

**Comment by agawronski** [comment]
Hi @drakemccabe, thank you for bringing this to my attention. I am unable to test that the fix for this works (only have access to redshift with a token), however I have released 1.1.2 correcting this issue. If could could upgrade, and let me know that it is working, that would be great. Thanks.

**Comment by drake-yesware** [comment]
@agawronski just upgraded and it looks like everything works as normal now. Thanks for the quick fix and for creating this package!

**Comment by agawronski** [comment]
No problem. Glad you like it!
