### ISSUE TITLE
Can't install pandas_redshift from circleci

### ISSUE THREAD

**Issue by alexisrosuel** [agawronski/pandas_redshift#2]
I am trying to setup circle ci for a project which uses pandas_redshift as a dependency, but it never find the package during pip install

### Expected Behaviour
`pip install -r requirements.txt `
with 
`pandas_redshift==1.1.0`
should install pandas_redshift in circle ci

### Actual Behaviour
I tried several combinaison (pandas-redshift and pandas_redshift, with and withour ==1.1.0)

![capture d ecran 2017-12-08 a 09 47 35](https://user-images.githubusercontent.com/19517275/33758069-11a8cb9e-dbfd-11e7-89f7-00a64526967e.png)
![capture d ecran 2017-12-08 a 09 48 02](https://user-images.githubusercontent.com/19517275/33758070-11c01b32-dbfd-11e7-92dc-06123e2f7a12.png)
![capture d ecran 2017-12-08 a 09 48 10](https://user-images.githubusercontent.com/19517275/33758071-11d6ae6a-dbfd-11e7-8761-065cd793f1a5.png)
![capture d ecran 2017-12-08 a 09 48 18](https://user-images.githubusercontent.com/19517275/33758072-11edc49c-dbfd-11e7-8533-fe867fc4d163.png)

### Steps to reproduce (If possible)
Set up a dummy project on circle with pandas_redshift in requirements.txt

Thanks !

**Comment by agawronski** [comment]
Hi Alexis,

I hit the same error testing locally when I try and install for python2 ... could this be the issue? Currently pandas_redshift is only compatible with python3 however I can probably make it compatible with python2 if there is demand.

requirements.txt should specify:

pandas-redshift==1.1.0

**Comment by alexisrosuel** [comment]
Hi agawronski, thanks for your answer !

My project is under python 3 also, but it seems that I made a mistake during the configuration of circleci...

Thanks again !

**Comment by agawronski** [comment]
No problem!
