### ISSUE TITLE
Support IAM role for S3

### ISSUE THREAD

**Issue by Gauravshah** [agawronski/pandas_redshift#25]
### Expected Behaviour
we should be able to use default IAM role instead of having hardcoded keys

### Actual Behaviour
we send in aws_keys via code

### commands that can be used
`boto3.client(  's3')` should automatically pick up IAM

**Comment by yaojiach** [comment]
I think if you just do: 
```python
connect_to_s3(aws_access_key_id=None, aws_secret_access_key=None, bucket='bucket')
```
`boto3` will default fall back to `.aws/credentials` first and then environment variables

**Comment by yaojiach** [comment]
Closing this issue as it can be done by passing `None` to the arguments.

**Comment by Gauravshah** [comment]
Thanks will give it a shot
