### ISSUE TITLE
Truncate Table

### ISSUE THREAD

**Issue by kokoro011** [agawronski/pandas_redshift#31]
Instead of dropping table and creating a new one, is there a way to truncate/delete all records in an existing table to then loading up the new data?

**Comment by agawronski** [comment]
I'm sure this is possible. Whether there is a benefit is debatable. From what I understand it is better to drop and create: "COPY loads large amounts of data much more efficiently than using INSERT statements, and stores the data more effectively as well." (https://docs.aws.amazon.com/redshift/latest/dg/c_best-practices-use-copy.html).

Is there a specific reason that it is better? @yaojiach do you have any thoughts on this?

**Comment by agawronski** [comment]
@kokoro011 was this request due to performance or another reason? Will be closing this issue if there is no benefit to truncation.

**Comment by yaojiach** [comment]
It could be helpful when you don't want to append to an existing table and don't want to re-specify the column types either.

Maybe we can run a `truncate` and then use `append = true` in this case.

**Comment by agawronski** [comment]
archiving repository
