### ISSUE TITLE
Convert pandas int to bigint as well

### ISSUE THREAD

**Issue by aharonen** [agawronski/pandas_redshift#35]
### Expected Behaviour
when pandas int is 64 convert it to redshift bigint when it is 32 convert it to int

### Actual Behaviour
all of the ints 64/32 convert to int

### Steps to reproduce (If possible)
def pd_dtype_to_redshift_dtype(dtype):
    if dtype.startswith('int64'):
        return 'bigint'

**Comment by agawronski** [comment]
Thank you @aharonen. I have updated the latest version from @mdarblade on PyPI and you should now find this fixed by running:
`pip3 install pandas-redshift --upgrade`

**Comment by aharonen** [comment]
well done thanks 👍
