### ISSUE TITLE
name 's3' is not defined

### ISSUE THREAD

**Issue by MikeCush** [agawronski/pandas_redshift#37]
### Expected Behaviour
Trying to use pandas_to_redshift to create a table from a dataframe.

### Actual Behaviour
pandas_to_redshift returning **NameError: name 's3' is not defined**.  Any idea how to fix the issue?  Thank you for looking into this.

**Comment by brucebismarck** [comment]
line 109.  s3.Bucket(s3_bucket_var).put_object( 

But s3 is not defined... before.

**Comment by brucebismarck** [comment]
I think the reason is to run connect_to_s3 first.  Then it will make s3 a global variable, and be used in the future.

**Comment by agawronski** [comment]
Closing due to lack of response.

**Comment by spaghetti-m0nster** [comment]
@brucebismarck is right you have to run

```
import pandas_redshift as pr

pr.connect_to_redshift(...)
pr.connect_to_s3(...)
df = p.read_csv('https://some-website/resource.csv')
pr.pandas_to_redshift(data_frame=df, redshift_table_name="...")

```
