### ISSUE TITLE
How to specify the schema on the connection?

### ISSUE THREAD

**Issue by godalida** [agawronski/pandas_redshift#41]
### Expected Behaviour
pr.connect_to_redshift(dbname =<dbname>,          ,
                        host = <host>,
                        port = 5439,
                        schema = <schema>,
                        user = <username>,
                        password = <pw>)

### Actual Behaviour
pr.connect_to_redshift(dbname =<dbname>,          ,
                        host = <host>,
                        port = 5439,
                        user = <username>,
                        password = <pw>)

**Comment by yaojiach** [comment]
`schema` is not currently implemented as an option. Is there a reason you want to avoid specifying the schema in your SQL queries instead? For example, `select * from schema.table`?

If we want to add this option, I think we can change `connect_to_redshift`:
```python
def connect_to_redshift(dbname, host, user, port=5439, schema='public', **kwargs):
    global connect, cursor
    connect = psycopg2.connect(dbname=dbname,
                               host=host,
                               port=port,
                               user=user,
                               schema=schema
                               **kwargs)
    cursor = connect.cursor()
    cursor.execute("SET search_path TO " + schema)
```
