### ISSUE TITLE
Is there a quick way to import .txt or .sql file into the redshift_to_pandas wrapper?

### ISSUE THREAD

**Issue by mwilson19** [agawronski/pandas_redshift#48]

**Comment by agawronski** [comment]
Hi mwilson19, I'm not sure that I understand your question? Seems like you could just do something like:

`data = pr.redshift_to_pandas(open('demofile.txt', 'r').read())`

That's untested, but I'm not quite sure what you're asking as I don't see how it could be quicker in a meaningful way.

**Comment by mwilson19** [comment]
Hi! sorry to be vague, but that's exactly right...for whatever reason that is giving me all heaps of trouble if i have multiple lines in the text file...i am not the best in python but i'll share example.  The second option below works perfectly fine if I embed the SQL to the wrapper function, but the moment i have in a text file call it fails.  Tried other read options as well.

`data = pr.redshift_to_pandas(open('import.txt', 'r').read())` I get thrown errors.


```
data = pr.redshift_to_pandas('''
  
  SELECT
  htls.curr_inn_code
 ,htls.curr_property_name
 ,brand.curr_brand_name
 ,mkt.curr_str_market_tract_name
 ,mkt2.curr_str_market_name
 ,htls.curr_state_desc
 ,htls.curr_gro_status
 ,htls.curr_is_rmcc
 ,mng.curr_management_type_desc
 
FROM revmgmt.dt_curr_property_h htls

INNER JOIN revmgmt.dt_curr_market_tract_h mkt ON mkt.curr_str_market_tract_nk = htls.curr_str_market_tract_nk
INNER JOIN revmgmt.dt_curr_str_h mkt2 ON mkt2.curr_str_market_nk = mkt.curr_str_market_nk
INNER JOIN revmgmt.dt_curr_brand_h brand ON brand.curr_sub_brand_nk = htls.curr_sub_brand_nk
INNER JOIN revmgmt.dt_comparability comp ON comp.facility_id = htls.facility_id
INNER JOIN revmgmt.dt_curr_management_h mng ON mng.curr_management_type_nk = htls.curr_management_type_nk

WHERE comp.Year = 2020
AND comp.curr_comparability = TRUE
AND mkt2.curr_str_market_name = 'Orlando, FL'

''')
```

**Comment by mwilson19** [comment]
hahaha nevermind...finally just worked, you have magic touch thank you.
