### ISSUE TITLE
Raise an error when something wrong occurs

### ISSUE THREAD

**Issue by alexisrosuel** [agawronski/pandas_redshift#5]
Hi ! Here is some missing feature I identified :

### Expected Behaviour
When loading any data in redshift using pandas_redshift, it would be great if an error is raised so that the python script stops when something wrong occurs.

### Actual Behaviour
With the current version, any fail during the import will log a warning message but will not terminate.

### Steps to reproduce (If possible)
I see at least two examples: 
- loading data with the right structure, with append=True in a non existing table 
- loading data where we mispecified the column type

**Comment by agawronski** [comment]
Thanks for opening the issue Alex. I'll try reproducing and handling this as soon as possible.

**Comment by agawronski** [comment]
Hi Alexis,

I have released v1.1.1 with a fix for these issues, please run:
pip install pandas-redshift --upgrade
