### ISSUE TITLE
Connection terminates if left open for a long time

### ISSUE THREAD

**Issue by zanynik** [agawronski/pandas_redshift#51]
It is good and an expected behaviour , just like what happens with sqlalchemny/psycopg2 package. 
But in other package there is an option of adding parameter :  "pool_pre_ping=True" which ensures the connection is kept alive until intentionally closed. It would be nice to have this feature in this package too. Thanks for making this package :).

**Comment by yaojiach** [comment]
Would you be willing to add this feature and PR?

**Comment by zanynik** [comment]
I don't think I have enough knowledge to do that. Sorry :(

**Comment by yaojiach** [comment]
Actually our `connect_to_redshift` function takes `kwarg` and passes them on to `psycopg2.connect`. So you could pass in any parameter that's supported.
