### ISSUE TITLE
Getting syntax error with every RDS exclusive query being run on Psycopg2

### ISSUE THREAD

**Issue by Pipe-Runner** [agawronski/pandas_redshift#52]
### Expected Behaviour
The queries that are being generated internally should work

### Actual Behaviour
Every keyword that is exclusive to RDS throws a syntax  error.

### Steps to reproduce (If possible)
Just run any data frame to RDS workflow.

**Comment by yaojiach** [comment]
RDS is not supported at all. You're welcome to add this support/feature and PR.

**Comment by Pipe-Runner** [comment]
Yup, I figured. I'll try to drop a PR for it.

**Comment by Pipe-Runner** [comment]
Hey, so I have created my own version for RDS postgres. But I am not sure how it will fit in with the project as it is specific to Redshift. Any suggestions? Or should I create my own fork? @yaojiach

**Comment by yaojiach** [comment]
https://github.com/agawronski/pandas_redshift/blob/master/CONTRIBUTING.md

**Comment by yaojiach** [comment]
Closing this since it's not really an issue and a PR for enhancement is likely on the way.
