### ISSUE TITLE
Writing to Logging File Disappears

### ISSUE THREAD

**Issue by h0wfr35** [agawronski/pandas_redshift#53]
### Expected Behaviour
I expected the being able to write to the logging file I specified to continue work as it did prior to adding the pandas_redshift library.

### Actual Behaviour
After adding the library, when I run the same script (but with new pr code added), it no longer outputs a log file

### Steps to reproduce (If possible)
the following code does not produce a log text file once "import pandas_redshift as pr" is added:

`   
    import boto3
    import pandas as pd
    import io
    import os
    from datetime import datetime
    from random import seed
    from random import random
    import logging

    # initialize log & start time
    time_start = datetime.now().strftime(format_datetime)
    path_log = os.path.join(cwd, 'log')
    logging.basicConfig(filename=os.path.join(path_log,
                                                          'hb_etl-' +
                                                          time_start.replace(' ', '_').replace('-', ''). replace(':', '') +
                                                          '.log'),
                                                          filemode='w',
                                                          format='%(asctime)s - %(message)s',
                                                          level=logging.DEBUG)
    logging.info('{0}'.format(time_start))`

**Comment by agawronski** [comment]
Can you include the definition of format_datetime?

**Comment by agawronski** [comment]
Also, there are no errors? Just no logs?

**Comment by h0wfr35** [comment]
Hi Aidan,

No errors at all, thankfully--just not seeing the logs that normally get
written in my log directory after adding the pandas-redshift library.
Really appreciate this library and your rapid response!

Regards,
Howard

**Comment by agawronski** [comment]
Np, still do need the definition of format_datetime to figure this out though.

**Comment by h0wfr35** [comment]
Sure, here it is:

format_datetime = '%Y-%m-%d %H:%M:%S'

**Comment by yaojiach** [comment]
I think this is due to how we set up logging, which is incorrect. I'll fix and submit PR.

**Comment by agawronski** [comment]
Thanks JC, you're the man. :100:

**Comment by agawronski** [comment]
release 2.0.5 is out on pypi with the changes to logging.

**Comment by h0wfr35** [comment]
Thank you so much for your super fast help!
