### ISSUE TITLE
Permission to Contribute - Implement Dask to Project

### ISSUE THREAD

**Issue by demousersrccode** [agawronski/pandas_redshift#55]
Hi, I was looking through your project and I have some ideas brewing on how to include a dask implementation to this project.
If you're ok with you can give me the thumbs up to go ahead.
Thanks

**Comment by agawronski** [comment]
I don't see why not. Can you list some of the improvements you were thinking of?

**Comment by demousersrccode** [comment]
Thank you, I tried using the package on a dask dataframe I worked on migrating to s3 but I got an error from the function df_to_s3 since the dataframe type is based on pandas core- I'll send in the error log on that but I kinda figured out a way to tune out that error; it's not really much all it takes is an if block condition to assert that the dataframe is of type dask rather than pandas

Also, I was wondering why the files waiting to be processed to the redshift table don't get deleted on the s3 bucket after migration is done. Is there a reason to that?
Thanks again for replying to this

**Comment by demousersrccode** [comment]
ill send a pr to you on this
