### ISSUE TITLE
What to do when "String length exceeds DDL length" ?

### ISSUE THREAD

**Issue by zanynik** [agawronski/pandas_redshift#57]
### Expected Behaviour

Upload the df to redshift

### Actual Behaviour

Gives the error if one of the column has a string length greater than default value of 256 characters.

### Steps to reproduce (If possible)

Upload a pandas df with a long text message ( > 256 characters). The upload fails because of the hardcoded value of 256 set in package

**Comment by yaojiach** [comment]
This is likely a Redshift issue. Here is a reference: https://stackoverflow.com/questions/54102184/postgresqlaws-redshift-error-1204-string-length-exceeds-ddl-length

**Comment by coder-nix** [comment]
We can increase the column length in redshift and make this error go away. 
But It would be nice if the uploading function of this package identifies the max length of each column in the pandas df and sets that max length (if greater than default) as the new column length value when creating redshift table.

**Comment by zanynik** [comment]
I solved this issue for me by changing varchar(256) to varchar(MAX) in the following code block of core.py
```
def pd_dtype_to_redshift_dtype(dtype):
    if dtype.startswith('int64'):
        return 'BIGINT'
    elif dtype.startswith('int'):
        return 'INTEGER'
    elif dtype.startswith('float'):
        return 'REAL'
    elif dtype.startswith('datetime'):
        return 'TIMESTAMP'
    elif dtype == 'bool':
        return 'BOOLEAN'
    else:
        return 'VARCHAR(256)'
```
` return 'VARCHAR(MAX)'`

**Comment by rudesai** [comment]
@agawronski @zanynik can you push the varchar(MAX) change to the main codebase? Any reason we limit it to 256 char?
