### ISSUE TITLE
InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

### ISSUE THREAD

**Issue by MohammedZayn** [agawronski/pandas_redshift#62]
### Expected Behaviour
the df is supposed to be put into a new table using the command pr.pandas_to_redshift(data_frame = leads,
                        redshift_table_name = 'cvm_only.test',
                        if_exist = 'false',
                        append = True)

### Actual Behaviour
however I get the following error:
InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

**Comment by agawronski** [comment]
archiving repository
